apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: index-web-ingress
  namespace: index-web
  annotations:
    cert-manager.io/cluster-issuer: "cert-manager"
spec:
  tls:
  - hosts:
    - k8dashboard.com
    secretName: demo-key
  rules:
  - host: "k8dashboard.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: index-web-service
            port:
              number: 80
