apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: index-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 10.80.9.251.nip.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: index-web-service
            port:
              number: 80:30004/TCP
